[package]
name = "imgui-winit-support"
version = "0.4.0-pre"
edition = "2018"
authors = ["Joonas Javanainen <joonas.javanainen@gmail.com>", "imgui-rs contributors"]
description = "winit support code for the imgui crate"
homepage = "https://github.com/Gekkio/imgui-rs"
repository = "https://github.com/Gekkio/imgui-rs"
license = "MIT/Apache-2.0"
categories = ["gui"]

[dependencies]
imgui = { version = "0.4.0-pre", path = "../" }
#winit-20 = { git="https://github.com/rust-windowing/winit.git", package = "winit", optional = true }
winit-20 = { version = ">= 0.20", package = "winit", optional = true }

[features]
default = ["winit-20"]
